name: 'GitVersion Action'
description: 'This GitHub Action extracts version information using GitVersion.'

inputs:
  useDefaultConfig:
    description: 'Whether to use the default GitVersion configuration'
    required: false
    default: 'true'
  configFilePath:
    description: 'Path to a custom GitVersion configuration file'
    required: false
    default: 'gitversion.yml'

# outputs:
#   gitversion-fullsemver:
#     description: 'FullSemVer from GitVersion'
#     value: ${{ steps.gitversion.outputs.fullSemVer }}
#   gitversion-sha:
#     description: 'Current commit SHA'
#     value: ${{ steps.gitversion.outputs.sha }}

runs:
  using: 'composite'
  steps:
    - name: Create default GitVersion config
      if: ${{ inputs.use-default-config == 'true' }}
      shell: bash
      run: |
            cat > gitversion.yml << 'EOF'
            workflow: GitHubFlow/v1
            
            tag-prefix: '[vV]'
            
            major-version-bump-message: '(BREAKING CHANGE|^.+!:)'
            minor-version-bump-message: '^feat(\([^)]+\))?:\s'
            patch-version-bump-message: '^(fix|perf|refactor|revert)(\([^)]+\))?:\s'
            no-bump-message: '^(chore|docs|style|test|ci)(\([^)]+\))?:\s'
            
            commit-message-incrementing: Enabled
            
            strategies:
              - MergeMessage
              - TaggedCommit
              - TrackReleaseBranches
              - VersionInBranchName
            
            branches:
              main:
                mode: ContinuousDeployment
                increment: Patch
                regex: ^master$|^main$
                is-main-branch: true
                
              release:
                mode: ContinuousDeployment
                increment: None
                regex: ^release/(?<BranchName>[0-9]+\.[0-9]+\.[0-9]+)$
                is-release-branch: true
              
              develop:
                mode: ContinuousDelivery
                increment: Minor
                regex: ^dev(elop)?(ment)?$

            commit-date-format: ddMMyyyy

            assembly-versioning-scheme: MajorMinorPatch
            assembly-informational-format: '{SemVer}'
            EOF

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v4
      with:
        versionSpec: '6.4.x'

    - name: Execute GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v4
      with:
        configFilePath: ${{ inputs.configFilePath }}

    - name: Set outputs
      shell: bash
      run: |
        echo "gitversion-fullsemver=${{ steps.gitversion.outputs.fullSemVer }}" >> $GITHUB_OUTPUT
        echo "gitversion-sha=${{ steps.gitversion.outputs.sha }}" >> $GITHUB_OUTPUT
